weatherapi:
  # Get the data back in F, not K
  url: http://api.openweathermap.org/data/2.5/weather?zip=%s,us&units=imperial&appid=%s
  # !!! The appid must be supplied, or this won't work
  appid: 

timezoneapi:
  # location=lat,lon
  url: https://maps.googleapis.com/maps/api/timezone/json?location=%s,%s&timestamp=%s&key=%s
  # !!! The appid must be supplied, or this won't work
  appid: 

elevationapi:
  # locations=lat,lon
  url: https://maps.googleapis.com/maps/api/elevation/json?locations=%s,%s&key=%s
  # !!! The appid must be supplied, or this won't work
  appid: 
